name: Run GetDailyArt Bot

on:
  # Run on push to main branch
  push:
    branches:
      - main
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'  # Runs at 00:00, 06:00, 12:00, 18:00 UTC
  # Allow manual trigger
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max 6 hours per job

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot==20.7 requests beautifulsoup4 python-dotenv

      # Run the bot with environment variables from secrets
      - name: Run GetDailyArt Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_VALID_USERS: ${{ secrets.TELEGRAM_VALID_USERS }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python bot.py